Repository CodeEditApp/CodeEdit, pull requests merged in 2022-03, with the labels that each got.

#44 Breadcrumbs Navigation
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit/Breadcrumbs/BreadcrumbsComponent.swift
  CodeEdit/Breadcrumbs/BreadcrumbsView.swift
  CodeEdit/Documents/WorkspaceDocument.swift
  CodeEdit/SideBar/SideBarItem.swift
  CodeEditModules/Modules/WorkspaceClient/src/Interface.swift
  CodeEditModules/Modules/WorkspaceClient/src/Live.swift
  CodeEditModules/Modules/WorkspaceClient/src/Mocks.swift
Labels: enhancement

#50 feat: added code editor
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit.xcodeproj/xcshareddata/xcschemes/CodeEdit.xcscheme
  CodeEdit.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CodeEdit/ContentView.swift
  CodeEdit/Documents/CodeEditDocumentController.swift
  CodeEdit/Documents/CodeFile.swift
  CodeEdit/Documents/WorkspaceDocument.swift
  CodeEdit/Editor/CodeFileEditor.swift
  CodeEdit/Editor/EditorView.swift
  CodeEdit/Editor/WorkspaceEditorView.swift
  CodeEdit/Info.plist
  CodeEdit/SideBar/SideBar.swift
  CodeEdit/SideBar/SideBarItem.swift
  CodeEditModules/Modules/CodeFile/Tests/UnitTests.swift
  CodeEditModules/Modules/CodeFile/Tests/__Snapshots__/UnitTests/testViewSnapshot.1.png
  CodeEditModules/Modules/CodeFile/src/CodeFile.swift
  CodeEditModules/Modules/CodeFile/src/CodeFileView.swift
  CodeEditModules/Modules/WorkspaceClient/src/Model/FileItem+Array.swift
  CodeEditModules/Modules/WorkspaceClient/src/Model/FileItem.swift
  CodeEditModules/Package.swift
Labels: enhancement

#63 fix: code-editor dark mode
  CodeEditModules/Modules/CodeFile/src/CodeFileView.swift
Labels: bug

#47 Welcome Window
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit/AppDelegate.swift
  CodeEdit/Documents/CodeEditDocumentController.swift
  CodeEdit/Welcome/RecentProjectsView.swift
  CodeEdit/Welcome/WelcomeView.swift
  CodeEdit/Welcome/WelcomeWindowView.swift
  CodeEditModules/Modules/WelcomeModule/Tests/UnitTests.swift
  CodeEditModules/Modules/WelcomeModule/Tests/__Snapshots__/UnitTests/testRecentProjectItemNormalSnapshot.1.png
  CodeEditModules/Modules/WelcomeModule/Tests/__Snapshots__/UnitTests/testRecentProjectItemSelectedSnapshot.1.png
  CodeEditModules/Modules/WelcomeModule/Tests/__Snapshots__/UnitTests/testWelcomeActionViewSnapshot.1.png
  CodeEditModules/Modules/WelcomeModule/src/RecentProjectItem.swift
  CodeEditModules/Modules/WelcomeModule/src/WelcomeActionView.swift
  CodeEditModules/Package.swift
Labels: enhancement

#68 Added Editor Theme Switcher to settings
  CodeEdit/Settings/GeneralSettingsView.swift
  CodeEditModules/Modules/CodeFile/src/CodeEditor+AppStorage.swift
  CodeEditModules/Modules/CodeFile/src/CodeFileView.swift
Labels: enhancement

#82 Improve welcome screen
  CodeEdit/AppDelegate.swift
  CodeEdit/MainMenu.xib
  CodeEdit/Welcome/RecentProjectsView.swift
  CodeEdit/Welcome/WelcomeView.swift
  CodeEditModules/Modules/WelcomeModule/Tests/UnitTests.swift
  CodeEditModules/Modules/WelcomeModule/Tests/__Snapshots__/UnitTests/testRecentJSFileDarkSnapshot.1.png
  CodeEditModules/Modules/WelcomeModule/Tests/__Snapshots__/UnitTests/testRecentJSFileLightSnapshot.1.png
  CodeEditModules/Modules/WelcomeModule/Tests/__Snapshots__/UnitTests/testRecentProjectItemDarkSnapshot.1.png
  CodeEditModules/Modules/WelcomeModule/Tests/__Snapshots__/UnitTests/testRecentProjectItemLightSnapshot.1.png
  CodeEditModules/Modules/WelcomeModule/Tests/__Snapshots__/UnitTests/testRecentProjectItemNormalSnapshot.1.png
  CodeEditModules/Modules/WelcomeModule/Tests/__Snapshots__/UnitTests/testRecentProjectItemSelectedSnapshot.1.png
  CodeEditModules/Modules/WelcomeModule/Tests/__Snapshots__/UnitTests/testWelcomeActionViewDarkSnapshot.1.png
  CodeEditModules/Modules/WelcomeModule/Tests/__Snapshots__/UnitTests/testWelcomeActionViewLightSnapshot.1.png
  CodeEditModules/Modules/WelcomeModule/Tests/__Snapshots__/UnitTests/testWelcomeActionViewSnapshot.1.png
  CodeEditModules/Modules/WelcomeModule/src/RecentProjectItem.swift
  CodeEditModules/Package.swift
Labels: enhancement

#91 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#99 Basic implementation of the status bar (non interactive)
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit/SideBar/SideBarItem.swift
  CodeEditModules/Modules/StatusBar/src/StatusBar.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarModel.swift
  CodeEditModules/Package.swift
Labels: enhancement, UI

#122 Set up Code of Conduct
  CODE_OF_CONDUCT.md
Labels: documentation

#119 Open Quickly
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit/AppDelegate.swift
  CodeEdit/Breadcrumbs/BreadcrumbsView.swift
  CodeEdit/Documents/CodeEditWindowController.swift
  CodeEdit/Documents/WorkspaceCodeFileView.swift
  CodeEdit/Documents/WorkspaceDocument.swift
  CodeEdit/MainMenu.xib
  CodeEdit/Quick Open/QuickOpenItem.swift
  CodeEdit/Quick Open/QuickOpenPreviewView.swift
  CodeEdit/Quick Open/QuickOpenView.swift
  CodeEdit/SideBar/SideBarItem.swift
  CodeEdit/WorkspaceView.swift
  CodeEditModules/Modules/CodeFile/src/CodeFile.swift
  CodeEditModules/Modules/CodeFile/src/CodeFileView.swift
  CodeEditModules/Modules/CodeFile/src/ThemedCodeView.swift
  CodeEditModules/Modules/Overlays/src/OverlayPanel.swift
  CodeEditModules/Package.swift
Labels: enhancement, UI

#138 Statusbar enhancement
  CodeEditModules/Modules/StatusBar/src/StatusBar.swift
Labels: UI

#159 Status Bar improvements (dragging drawer)
  CodeEditModules/Modules/StatusBar/src/Model/StatusBarModel.swift
  CodeEditModules/Modules/StatusBar/src/Model/View+isHovering.swift
  CodeEditModules/Modules/StatusBar/src/StatusBar.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarItems/StatusBarBranchPicker.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarItems/StatusBarCursorLocationLabel.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarItems/StatusBarDrawer.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarItems/StatusBarEncodingSelector.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarItems/StatusBarIndentSelector.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarItems/StatusBarLabelButton.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarItems/StatusBarLineEndSelector.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarItems/StatusBarPullButton.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarItems/StatusBarToggleDrawerButton.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarModel.swift
Labels: UI

#161 Updated `CONTRIBUTING.md` with more detailed info
  CONTRIBUTING.md
Labels: documentation

#164 Context Menu Basics
  CodeEdit/NavigatorSidebar/NavigatorSidebarItem.swift
  CodeEditModules/Modules/WorkspaceClient/src/Model/FileItem.swift
Labels: enhancement, UI

#125 Finding in workspace
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit/Documents/String+Ranges.swift
  CodeEdit/Documents/WorkspaceDocument.swift
  CodeEdit/NavigatorSidebar/NavigatorSidebar.swift
  CodeEdit/NavigatorSidebar/Search/SearchBar.swift
  CodeEdit/NavigatorSidebar/Search/SearchModeSelector.swift
  CodeEdit/NavigatorSidebar/Search/SearchResultFileItem.swift
  CodeEdit/NavigatorSidebar/Search/SearchResultList.swift
  CodeEdit/NavigatorSidebar/Search/SidebarSearch.swift
  CodeEditModules/Modules/Search/src/Model/SearchModeModel.swift
  CodeEditModules/Modules/Search/src/Model/SearchResultModel.swift
  CodeEditModules/Package.swift
Labels: enhancement, UI

#193 Fix `Fatal not a git repository`
  CodeEditModules/Modules/StatusBar/src/Model/StatusBarModel.swift
  CodeEditModules/Modules/StatusBar/src/StatusBar.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarItems/StatusBarBranchPicker.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarItems/StatusBarPullButton.swift
Labels: bug, UI

#197 Sidebar fixes
  CodeEdit/NavigatorSidebar/NavigatorSidebar.swift
  CodeEdit/NavigatorSidebar/NavigatorSidebarToolbarTop.swift
Labels: bug, UI

#186 Added scrollable breadcrumb, fixed sidebar moving to far left
  CodeEdit.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CodeEdit/Breadcrumbs/BreadcrumbsView.swift
  CodeEdit/WorkspaceView.swift
Labels: bug, UI

#165 Added basic implementation of a terminal emulator using `SwiftTerm`
  CodeEdit.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CodeEdit/CodeEdit.entitlements
  CodeEdit/Documents/WorkspaceCodeFileView.swift
  CodeEdit/Localization/de.lproj/Localizable.strings
  CodeEdit/Localization/en.lproj/Localizable.strings
  CodeEdit/Settings/GeneralSettingsView.swift
  CodeEditModules/Modules/StatusBar/src/Model/StatusBarModel.swift
  CodeEditModules/Modules/StatusBar/src/StatusBar.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarItems/StatusBarDrawer.swift
  CodeEditModules/Modules/TerminalEmulator/src/TerminalEmulatorView.swift
  CodeEditModules/Modules/TerminalEmulator/src/TerminalShellType.swift
  CodeEditModules/Package.swift
Labels: enhancement, UI

#206 fixed welcome window shortcut
  CodeEdit/MainMenu.xib
Labels: bug

#211 added font picker for terminal emulator
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit/Localization/de.lproj/Localizable.strings
  CodeEdit/Localization/en.lproj/Localizable.strings
  CodeEdit/Settings/GeneralSettingsView.swift
  CodeEdit/Settings/SettingsView.swift
  CodeEdit/Settings/TerminalSettingsView.swift
  CodeEditModules/Modules/FontPicker/src/FontPickerView.swift
  CodeEditModules/Modules/TerminalEmulator/src/TerminalEmulatorView.swift
  CodeEditModules/Modules/TerminalEmulator/src/TerminalFont.swift
  CodeEditModules/Package.swift
Labels: enhancement, UI

#231 Custom(izable) Navigator Sidebar Implementation
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit/NavigatorSidebar/FindNavigator/FindNavigator.swift
  CodeEdit/NavigatorSidebar/FindNavigator/FindNavigatorModeSelector.swift
  CodeEdit/NavigatorSidebar/FindNavigator/FindNavigatorResultFileItem.swift
  CodeEdit/NavigatorSidebar/FindNavigator/FindNavigatorResultList.swift
  CodeEdit/NavigatorSidebar/FindNavigator/FindNavigatorSearchBar.swift
  CodeEdit/NavigatorSidebar/LeadingSidebar.swift
  CodeEdit/NavigatorSidebar/LeadingSidebarToolbarBottom.swift
  CodeEdit/NavigatorSidebar/LeadingSidebarToolbarTop.swift
  CodeEdit/NavigatorSidebar/NavigatorSidebar.swift
  CodeEdit/NavigatorSidebar/NavigatorSidebarItem.swift
  CodeEdit/NavigatorSidebar/ProjectNavigator/ProjectNavigator.swift
  CodeEdit/NavigatorSidebar/ProjectNavigator/ProjectNavigatorItem.swift
  CodeEdit/WorkspaceView.swift
Labels: enhancement, UI

#227 ANSI Color Selector for Terminal & Terminal/Statusbar fixes
  CodeEdit/Documents/WorkspaceCodeFileView.swift
  CodeEdit/Settings/SettingsView.swift
  CodeEdit/Settings/TerminalSettingsView.swift
  CodeEdit/WorkspaceView.swift
  CodeEditModules/Modules/StatusBar/src/Model/StatusBarModel.swift
  CodeEditModules/Modules/StatusBar/src/StatusBar.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarItems/StatusBarDrawer.swift
  CodeEditModules/Modules/TerminalEmulator/src/Extensions/SwiftTerm+Color+Init.swift
  CodeEditModules/Modules/TerminalEmulator/src/Model/AnsiColors.swift
  CodeEditModules/Modules/TerminalEmulator/src/Model/TerminalFont.swift
  CodeEditModules/Modules/TerminalEmulator/src/Model/TerminalShellType.swift
  CodeEditModules/Modules/TerminalEmulator/src/TerminalEmulatorView+Coordinator.swift
  CodeEditModules/Modules/TerminalEmulator/src/TerminalEmulatorView.swift
Labels: UI, performance

#226 Remember state: open projects which were not closed by the user
  CodeEdit/AppDelegate.swift
  CodeEdit/Documents/CodeEditDocumentController.swift
  CodeEdit/Documents/WorkspaceDocument.swift
  CodeEdit/Welcome/RecentProjectsView.swift
Labels: enhancement

#263 Terminal Emulator: setting for custom terminal appearance
  CodeEdit/Settings/SettingsView.swift
  CodeEdit/Settings/TerminalSettingsView.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarItems/StatusBarDrawer.swift
  CodeEditModules/Modules/TerminalEmulator/src/Model/AnsiColors.swift
  CodeEditModules/Modules/TerminalEmulator/src/Model/TerminalColorScheme.swift
  CodeEditModules/Modules/TerminalEmulator/src/TerminalEmulatorView.swift
Labels: UI

#265 Project Navigator: fixed yellow color being low contrast in light mode
  CodeEdit/Assets.xcassets/SidebarYellow.colorset/Contents.json
  CodeEditModules/Modules/WorkspaceClient/src/Model/FileItem.swift
Labels: bug, UI

#269 Use a UUID string as identifier for `NSToolbar`
  CodeEdit.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CodeEdit/Documents/WorkspaceDocument.swift
Labels: bug, UI

#297 Added `TabWidth` selector to status bar
  CodeEdit/Settings/GeneralSettingsView.swift
  CodeEditModules/Modules/CodeFile/src/TextView/CodeEditorTextView.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarItems/StatusBarIndentSelector.swift
  CodeEditModules/Package.swift
Labels: enhancement, UI

#299 Added `isPressed` state to toolbar buttons in navigator sidebar
  CodeEdit/NavigatorSidebar/NavigatorSidebarToolbarTop.swift
Labels: UI

#249 Add breadcrumb dropdown menu
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit/Breadcrumbs/BreadcrumbsComponent.swift
  CodeEdit/Breadcrumbs/BreadcrumbsMenu.swift
  CodeEdit/Breadcrumbs/BreadcrumbsView.swift
  CodeEdit/Documents/WorkspaceDocument.swift
  CodeEditModules/Modules/WorkspaceClient/src/Live.swift
  CodeEditModules/Modules/WorkspaceClient/src/Model/FileItem.swift
Labels: enhancement, UI

#310 File Icon Colors in Tab Bar
  CodeEdit/TabBar/TabBarItem.swift
Labels: UI

#331 Preferences/Settings: Basic implementation
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CodeEdit/AppDelegate.swift
  CodeEdit/Breadcrumbs/BreadcrumbsComponent.swift
  CodeEdit/NavigatorSidebar/ProjectNavigator/ProjectNavigatorItem.swift
  CodeEdit/Settings/GeneralSettingsView.swift
  CodeEdit/Settings/Models/FileIconStyle.swift
  CodeEdit/Settings/SettingsView.swift
  CodeEdit/TabBar/TabBarItem.swift
  CodeEdit/Welcome/WelcomeView.swift
  CodeEditModules/Modules/AppPreferences/src/Model/Appearances.swift
  CodeEditModules/Modules/AppPreferences/src/Model/FileIconStyle.swift
  CodeEditModules/Modules/AppPreferences/src/Model/ReopenBehavior.swift
  CodeEditModules/Modules/AppPreferences/src/PreferencesGeneralView.swift
  CodeEditModules/Modules/AppPreferences/src/PreferencesPlaceholderView.swift
  CodeEditModules/Modules/AppPreferences/src/PreferencesTextEditingView.swift
  CodeEditModules/Modules/AppPreferences/src/PreferencesThemeView.swift
  CodeEditModules/Package.swift
Labels: UI, PRIORITY
