Repository CodeEditApp/CodeEdit, pull requests merged in 2022-05, with the labels that each got.

#562 Optimize Native Tab Bar Style, Fix Bugs, and Add Accessory Icons.
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit/Documents/WorkspaceCodeFileView.swift
  CodeEdit/Documents/WorkspaceDocument.swift
  CodeEdit/TabBar/TabBar.swift
  CodeEdit/TabBar/TabBarAccessory.swift
  CodeEdit/TabBar/TabBarDivider.swift
  CodeEdit/TabBar/TabBarItem.swift
  CodeEdit/TabBar/TabBarNative.swift
  CodeEdit/TabBar/TabBarXcode.swift
  CodeEdit/WorkspaceView.swift
  CodeEditModules/Modules/Breadcrumbs/src/BreadcrumbsView.swift
Labels: UI, tabs

#573 Tests: Added for `CodeEditUtils` Module
  CodeEdit.xcodeproj/xcshareddata/xcschemes/CodeEdit.xcscheme
  CodeEdit/Info.plist
  CodeEditModules/Modules/Acknowledgements/src/AcknowledgementsView.swift
  CodeEditModules/Modules/CodeEditUtils/Tests/UnitTests_Extensions.swift
  CodeEditModules/Modules/CodeEditUtils/src/Extensions/Date+Formatted.swift
  CodeEditModules/Modules/CodeEditUtils/src/Extensions/String+MD5.swift
  CodeEditModules/Package.swift
Labels: documentation, tests

#574 `CodeEditUtils`: added opacity to hex color inits
  CodeEdit/Info.plist
  CodeEditModules/Modules/CodeEditUtils/Tests/UnitTests_Extensions.swift
  CodeEditModules/Modules/CodeEditUtils/src/Extensions/Color+HEX.swift
Labels: documentation, tests

#575 `Acknowledgements`: Moved logic to `AcknowledgementModel`
  CodeEdit/Info.plist
  CodeEditModules/Modules/Acknowledgements/src/AcknowledgementsView.swift
  CodeEditModules/Modules/Acknowledgements/src/Model/AcknowledgementsModel.swift
Labels: Other

#577 `AboutView`: Code Clean-Up
  CodeEdit/Info.plist
  CodeEditModules/Modules/About/src/AboutView.swift
  CodeEditModules/Modules/CodeEditUtils/src/Extensions/Bundle+Info.swift
  CodeEditModules/Package.swift
Labels: Other

#580 Non editor tabs
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit/Documents/CodeEditWindowController.swift
  CodeEdit/Documents/WorkspaceCodeFileView.swift
  CodeEdit/Documents/WorkspaceDocument+Search.swift
  CodeEdit/Documents/WorkspaceDocument+Selection.swift
  CodeEdit/Documents/WorkspaceDocument.swift
  CodeEdit/Info.plist
  CodeEdit/InspectorSidebar/InspectorSidebar.swift
  CodeEdit/NavigatorSidebar/ExtensionNavigator/ExtensionInstallationView.swift
  CodeEdit/NavigatorSidebar/ExtensionNavigator/ExtensionInstallationViewModel.swift
  CodeEdit/NavigatorSidebar/ExtensionNavigator/ExtensionNavigatorItem.swift
  CodeEdit/NavigatorSidebar/FindNavigator/FindNavigatorResultList.swift
  CodeEdit/NavigatorSidebar/ProjectNavigator/OutlineView/OutlineViewController.swift
  CodeEdit/TabBar/TabBar.swift
  CodeEdit/TabBar/TabBarItem.swift
  CodeEdit/WorkspaceView.swift
  CodeEditModules/Modules/ExtensionsStore/src/Models/Plugin.swift
  CodeEditModules/Modules/TabBar/src/Documentation.docc/Adding New Tab Type.md
  CodeEditModules/Modules/TabBar/src/Documentation.docc/Documentation.md
  CodeEditModules/Modules/TabBar/src/TabBarItemID.swift
  CodeEditModules/Modules/TabBar/src/TabBarItemRepresentable.swift
  CodeEditModules/Modules/WorkspaceClient/src/Model/FileItem.swift
  CodeEditModules/Package.swift
Labels: enhancement, UI, tabs

#581 Add Find Navigator Result reflect general preference "Find Navigator Detail"
  CodeEdit/NavigatorSidebar/FindNavigator/FindNavigatorResultFileItem.swift
  CodeEditModules/Modules/AppPreferences/src/Sections/GeneralPreferences/GeneralPreferencesView.swift
Labels: WIP

#583 `Tabbar`: Accessory Button enhancements
  CodeEdit/Info.plist
  CodeEdit/TabBar/TabBar.swift
  CodeEdit/TabBar/TabBarAccessory.swift
Labels: UI, tabs

#584 `StatusBar`: Code Cleanup
  CodeEdit/Info.plist
  CodeEditModules/Modules/StatusBar/src/StatusBarDrawer/BottomBar/FilterTextField.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarDrawer/BottomBar/StatusBarClearButton.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarDrawer/BottomBar/StatusBarMaximizeButton.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarDrawer/BottomBar/StatusBarSplitTerminalButton.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarDrawer/StatusBarDrawer.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarItems/StatusBarBranchPicker.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarItems/StatusBarPullButton.swift
Labels: statusbar

#606 Fixed Statusbar Divider Color
  CodeEditModules/Modules/CodeEditUI/src/PanelDivider.swift
  CodeEditModules/Modules/StatusBar/src/StatusBar.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarItems/StatusBarCursorLocationLabel.swift
Labels: UI, statusbar

#607 Remove "unhandled files" warning
  CodeEdit/Info.plist
  CodeEditModules/Package.swift
Labels: tests

#608 StatusBar: Cleanup & Tests
  CodeEdit.xcodeproj/xcshareddata/xcschemes/CodeEdit.xcscheme
  CodeEdit/Documents/WorkspaceDocument.swift
  CodeEdit/Info.plist
  CodeEditModules/Modules/StatusBar/Tests/UnitTests.swift
  CodeEditModules/Modules/StatusBar/Tests/__Snapshots__/UnitTests/testStatusBarCollapsedDark.1.png
  CodeEditModules/Modules/StatusBar/Tests/__Snapshots__/UnitTests/testStatusBarCollapsedLight.1.png
  CodeEditModules/Modules/StatusBar/Tests/__Snapshots__/UnitTests/testStatusBarExpandedDark.1.png
  CodeEditModules/Modules/StatusBar/Tests/__Snapshots__/UnitTests/testStatusBarExpandedLight.1.png
  CodeEditModules/Modules/StatusBar/src/Extensions/View+isHovering.swift
  CodeEditModules/Modules/StatusBar/src/Model/CursorLocation.swift
  CodeEditModules/Modules/StatusBar/src/Model/StatusBarModel.swift
  CodeEditModules/Modules/StatusBar/src/Model/StatusBarTabType.swift
  CodeEditModules/Modules/StatusBar/src/StatusBar.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarDrawer/BottomBar/StatusBarClearButton.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarDrawer/BottomBar/StatusBarMaximizeButton.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarDrawer/BottomBar/StatusBarSplitTerminalButton.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarItems/StatusBarBreakpointButton.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarItems/StatusBarCursorLocationLabel.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarItems/StatusBarLabelButton.swift
  CodeEditModules/Package.swift
Labels: documentation, statusbar, tests

#642 [`feature/new-editor`]: implemented `CodeEditTextView`
  CodeEdit.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CodeEdit/Info.plist
  CodeEditModules/Modules/AppPreferences/src/Model/Text Editing/TextEditingPreferences.swift
  CodeEditModules/Modules/AppPreferences/src/Sections/ThemePreferences/Model/Theme.swift
  CodeEditModules/Modules/CodeFile/src/CodeEditor.swift
  CodeEditModules/Modules/CodeFile/src/CodeFileView.swift
  CodeEditModules/Modules/CodeFile/src/LineGutter/LineGutter.swift
  CodeEditModules/Modules/CodeFile/src/Model/CodeLanguage.swift
  CodeEditModules/Modules/CodeFile/src/Model/HighlightrLanguage.swift
  CodeEditModules/Modules/CodeFile/src/TextView/CodeEditorTextView.swift
  CodeEditModules/Package.swift
  Package.resolved
Labels: editor
