Repository CodeEditApp/CodeEdit, pull requests merged in 2022-09, with the labels that each got.

#742 add uuid to FileItem
  CodeEdit/Info.plist
  CodeEditModules/Modules/WorkspaceClient/src/Model/FileItem.swift
Labels: bug

#747 [fix]: disable failing snapshot unit tests
  CodeEdit.xcodeproj/xcshareddata/xcschemes/CodeEdit.xcscheme
  CodeEdit/Info.plist
Labels: tests

#601 Tab Bar Reordering Behavior and Bug Fixes
  CodeEdit/TabBar/TabBar.swift
  CodeEdit/TabBar/TabBarItem.swift
  CodeEdit/TabBar/TabBarItemButtonStyle.swift
Labels: UI, tabs, WIP
