Repository CodeEditApp/CodeEdit, pull requests merged in 2022-10, with the labels that each got.

#824 Disable unimplemented buttons
  CodeEdit/NavigatorSidebar/NavigatorSidebarToolbarTop.swift
Labels: UI

#827 Moved Themes and Preferences to Application Support
  CodeEditModules/Modules/AppPreferences/src/Documentation.docc/AppPreferences.md
  CodeEditModules/Modules/AppPreferences/src/Documentation.docc/Themes.md
  CodeEditModules/Modules/AppPreferences/src/Model/AppPreferences.swift
  CodeEditModules/Modules/AppPreferences/src/Model/AppPreferencesModel.swift
  CodeEditModules/Modules/AppPreferences/src/Sections/ThemePreferences/Model/ThemeModel.swift
Labels: chore

#843 [chore]: Update `CodeEditTextView` dependency
  CodeEdit.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CodeEditModules/Modules/AppPreferences/src/Documentation.docc/Themes.md
  CodeEditModules/Modules/AppPreferences/src/Sections/ThemePreferences/Model/Theme+Highlightr.swift
  CodeEditModules/Modules/CodeFile/src/CodeFileView.swift
  CodeEditModules/Package.swift
  Package.resolved
Labels: enhancement, performance, PRIORITY
