Repository CodeEditApp/CodeEdit, pull requests merged in 2022-04, with the labels that each got.

#343 Preferences: New UI, Theme Pane implementation, Persistence to `~/.codeedit/` Folder
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit/AppDelegate.swift
  CodeEdit/Breadcrumbs/BreadcrumbsComponent.swift
  CodeEdit/DefaultThemes/default-dark.json
  CodeEdit/Info.plist
  CodeEdit/NavigatorSidebar/ProjectNavigator/ProjectNavigatorItem.swift
  CodeEdit/TabBar/TabBarItem.swift
  CodeEdit/Welcome/WelcomeView.swift
  CodeEditModules/Modules/AppPreferences/src/Extensions/Color+HEX.swift
  CodeEditModules/Modules/AppPreferences/src/GeneralPreferences/PreferencesGeneralView.swift
  CodeEditModules/Modules/AppPreferences/src/HelperViews/HelpButton.swift
  CodeEditModules/Modules/AppPreferences/src/HelperViews/PreferencesColorPicker.swift
  CodeEditModules/Modules/AppPreferences/src/HelperViews/SegmentedControl.swift
  CodeEditModules/Modules/AppPreferences/src/Model/AppPreferences.swift
  CodeEditModules/Modules/AppPreferences/src/Model/AppPreferencesModel.swift
  CodeEditModules/Modules/AppPreferences/src/Model/Appearances.swift
  CodeEditModules/Modules/AppPreferences/src/Model/FileIconStyle.swift
  CodeEditModules/Modules/AppPreferences/src/Model/ReopenBehavior.swift
  CodeEditModules/Modules/AppPreferences/src/PreferencesGeneralView.swift
  CodeEditModules/Modules/AppPreferences/src/PreferencesTextEditingView.swift
  CodeEditModules/Modules/AppPreferences/src/PreferencesThemeView.swift
  CodeEditModules/Modules/AppPreferences/src/TerminalPreferences/PreferencesTerminalView.swift
  CodeEditModules/Modules/AppPreferences/src/TextEditingPreferences/PreferencesTextEditingView.swift
  CodeEditModules/Modules/AppPreferences/src/ThemePreferences/EditorThemeView.swift
  CodeEditModules/Modules/AppPreferences/src/ThemePreferences/Model/Theme.swift
  CodeEditModules/Modules/AppPreferences/src/ThemePreferences/Model/ThemeModel.swift
  CodeEditModules/Modules/AppPreferences/src/ThemePreferences/PreviewThemeView.swift
  CodeEditModules/Modules/AppPreferences/src/ThemePreferences/TerminalThemeView.swift
  CodeEditModules/Modules/AppPreferences/src/ThemePreferences/ThemePreferencesView.swift
  CodeEditModules/Modules/AppPreferences/src/ThemePreferences/ThemePreviewIcon.swift
  CodeEditModules/Modules/CodeFile/src/Model/EditorTabWidth.swift
  CodeEditModules/Modules/CodeFile/src/TextView/CodeEditorTextView.swift
  CodeEditModules/Modules/FontPicker/src/FontPickerView.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarItems/StatusBarIndentSelector.swift
  CodeEditModules/Modules/TerminalEmulator/src/Extensions/SwiftTerm+Color+Init.swift
  CodeEditModules/Modules/TerminalEmulator/src/Model/AnsiColors.swift
  CodeEditModules/Modules/TerminalEmulator/src/Model/TerminalColorScheme.swift
  CodeEditModules/Modules/TerminalEmulator/src/Model/TerminalFont.swift
  CodeEditModules/Modules/TerminalEmulator/src/Model/TerminalShellType.swift
  CodeEditModules/Modules/TerminalEmulator/src/TerminalEmulatorView.swift
  CodeEditModules/Package.swift
Labels: enhancement, UI

#383 🛠 Preferences: added locations section, more cohesive layout of labels
  CodeEdit/AppDelegate.swift
  CodeEdit/Info.plist
  CodeEditModules/Modules/AppPreferences/src/Extensions/Loopable.swift
  CodeEditModules/Modules/AppPreferences/src/GeneralPreferences/PreferencesGeneralView.swift
  CodeEditModules/Modules/AppPreferences/src/HelperViews/PreferencesSection.swift
  CodeEditModules/Modules/AppPreferences/src/LocationsPreferences/PreferencesLocationsView.swift
  CodeEditModules/Modules/AppPreferences/src/Model/AppPreferencesModel.swift
  CodeEditModules/Modules/AppPreferences/src/TerminalPreferences/PreferencesTerminalView.swift
  CodeEditModules/Modules/AppPreferences/src/TextEditingPreferences/PreferencesTextEditingView.swift
  CodeEditModules/Modules/AppPreferences/src/ThemePreferences/Model/ThemeModel.swift
Labels: UI

#384 Breadcrumbs: fix menu position after resizing window
  CodeEdit/Breadcrumbs/BreadcrumbsComponent.swift
  CodeEdit/Info.plist
Labels: bug, UI

#388 Terminal: hook up terminal colors to selected theme
  CodeEdit/Info.plist
  CodeEditModules/Modules/TerminalEmulator/src/TerminalEmulatorView.swift
Labels: UI, drawer, preferences

#390 Preferences: Added Terminal setting for `⌥/meta` key. Future proving decoding.
  CodeEdit/Info.plist
  CodeEditModules/Modules/AppPreferences/src/Model/AppPreferences.swift
  CodeEditModules/Modules/AppPreferences/src/TerminalPreferences/PreferencesTerminalView.swift
  CodeEditModules/Modules/TerminalEmulator/src/TerminalEmulatorView.swift
Labels: preferences

#399 Status Bar: Fix drawer in multiple workspaces
  CodeEdit/Info.plist
  CodeEditModules/Modules/StatusBar/src/Model/StatusBarModel.swift
  CodeEditModules/Modules/StatusBar/src/StatusBar.swift
  CodeEditModules/Modules/TerminalEmulator/src/TerminalEmulatorView+Coordinator.swift
  CodeEditModules/Modules/TerminalEmulator/src/TerminalEmulatorView.swift
Labels: bug, statusbar, drawer

#398 Documentation: Font Picker
  CodeEdit.xcodeproj/project.pbxproj
  CodeEditModules/Modules/FontPicker/src/Documentation.docc/Documentation.md
  CodeEditModules/Modules/FontPicker/src/FontPickerView.swift
Labels: documentation

#404 Fix sort and clear recent projects
  CodeEdit/Documents/CodeEditDocumentController.swift
  CodeEdit/Info.plist
Labels: bug

#413 Improved docs for `Theme` in `AppPreferences` module
  CodeEdit/Info.plist
  CodeEditModules/Modules/AppPreferences/src/Documentation.docc/Themes.md
Labels: documentation

#411 New implementation of Project Navigator - Performance Improvements
  .swiftlint.yml
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit/AppDelegate.swift
  CodeEdit/Info.plist
  CodeEdit/NavigatorSidebar/NavigatorSidebar.swift
  CodeEdit/NavigatorSidebar/ProjectNavigator/OutlineView/OutlineMenu.swift
  CodeEdit/NavigatorSidebar/ProjectNavigator/OutlineView/OutlineTableViewCell.swift
  CodeEdit/NavigatorSidebar/ProjectNavigator/OutlineView/OutlineView.swift
  CodeEdit/NavigatorSidebar/ProjectNavigator/OutlineView/OutlineViewController.swift
  CodeEdit/NavigatorSidebar/ProjectNavigator/ProjectNavigator.swift
  CodeEdit/NavigatorSidebar/ProjectNavigator/ProjectNavigatorContextMenu.swift
  CodeEdit/NavigatorSidebar/ProjectNavigator/ProjectNavigatorItem.swift
  CodeEditModules/Modules/WorkspaceClient/src/Live.swift
  CodeEditModules/Modules/WorkspaceClient/src/Model/FileItem.swift
Labels: bug, performance, navigator

#415 Documentation: `WorkspaceClient.FileItem`
  CodeEdit/Breadcrumbs/BreadcrumbsMenu.swift
  CodeEdit/Info.plist
  CodeEdit/NavigatorSidebar/FindNavigator/FindNavigatorResultFileItem.swift
  CodeEditModules/Modules/WorkspaceClient/src/Model/FileItem+Array.swift
  CodeEditModules/Modules/WorkspaceClient/src/Model/FileItem.swift
Labels: documentation

#417 Project Navigator: Fixed icon/label alignments & sizes
  CodeEdit/Info.plist
  CodeEdit/NavigatorSidebar/ProjectNavigator/OutlineView/OutlineTableViewCell.swift
Labels: UI, navigator

#416 Demo Extension API (Swift) and Extension Store
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CodeEdit/AppDelegate.swift
  CodeEdit/CodeEdit.entitlements
  CodeEdit/Documents/WorkspaceDocument.swift
  CodeEdit/Extensions/CodeEditAPI.swift
  CodeEdit/Extensions/CodeEditTargetsAPI.swift
  CodeEdit/Info.plist
  CodeEdit/NavigatorSidebar/ExtensionNavigator/ExtensionInstallationView.swift
  CodeEdit/NavigatorSidebar/ExtensionNavigator/ExtensionInstallationViewModel.swift
  CodeEdit/NavigatorSidebar/ExtensionNavigator/ExtensionNavigator.swift
  CodeEdit/NavigatorSidebar/ExtensionNavigator/ExtensionNavigatorData.swift
  CodeEdit/NavigatorSidebar/ExtensionNavigator/ExtensionNavigatorItem.swift
  CodeEdit/NavigatorSidebar/NavigatorSidebar.swift
  CodeEditModules/Modules/ExtensionsStore/src/API/ExtensionsStoreAPI.swift
  CodeEditModules/Modules/ExtensionsStore/src/API/Page.swift
  CodeEditModules/Modules/ExtensionsStore/src/API/Response.swift
  CodeEditModules/Modules/ExtensionsStore/src/ExtensionsManager.swift
  CodeEditModules/Modules/ExtensionsStore/src/Models/DownloadedPlugin.swift
  CodeEditModules/Modules/ExtensionsStore/src/Models/Plugin.swift
  CodeEditModules/Modules/ExtensionsStore/src/Models/PluginRelease.swift
  CodeEditModules/Package.swift
Labels: enhancement, extensions

#418 `Project Navigator`: Implemented Setting for changing Item Size
  CodeEdit/Info.plist
  CodeEdit/NavigatorSidebar/ProjectNavigator/OutlineView/OutlineTableViewCell.swift
  CodeEdit/NavigatorSidebar/ProjectNavigator/OutlineView/OutlineView.swift
  CodeEdit/NavigatorSidebar/ProjectNavigator/OutlineView/OutlineViewController.swift
  CodeEditModules/Modules/AppPreferences/src/Model/AppPreferences.swift
  CodeEditModules/Modules/AppPreferences/src/Sections/GeneralPreferences/GeneralPreferencesView.swift
Labels: UI, navigator

#422 Load extensions in the main thread
  CodeEdit/AppDelegate.swift
Labels: bug, extensions

#232 Add functionality for cloning from git in welcome view
  CodeEdit.xcodeproj/project.pbxproj
  CodeEditModules/Modules/GitClient/src/Interface.swift
  CodeEditModules/Modules/GitClient/src/Live.swift
  CodeEditModules/Modules/GitClone/src/GitCloneView.swift
  CodeEditModules/Modules/WelcomeModule/src/WelcomeView.swift
  CodeEditModules/Package.swift
Labels: enhancement, UI, WIP

#441 BUG: fixed UI inconsistencies in `Accounts` and `Source Control` preferences
  CodeEdit/Info.plist
  CodeEditModules/Modules/AppPreferences/src/HelperViews/PreferencesToolbar.swift
  CodeEditModules/Modules/AppPreferences/src/Sections/AccountsPreferences/PreferenceAccountsView.swift
  CodeEditModules/Modules/AppPreferences/src/Sections/SourceControlPreferences/PreferenceSourceControlView.swift
  CodeEditModules/Modules/AppPreferences/src/Sections/SourceControlPreferences/SourceControlGeneralView.swift
  CodeEditModules/Modules/AppPreferences/src/Sections/SourceControlPreferences/SourceControlGitView.swift
  CodeEditModules/Modules/AppPreferences/src/Sections/ThemePreferences/ThemePreferencesView.swift
Labels: UI, preferences

#451 Feedback Window for CodeEdit
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit/AppDelegate.swift
  CodeEdit/Info.plist
  CodeEdit/MainMenu.xib
  CodeEditModules/Modules/Feedback/src/Controllers/FeedbackWindowController.swift
  CodeEditModules/Modules/Feedback/src/FeedbackView.swift
  CodeEditModules/Modules/Feedback/src/HelperView/FeedbackToolbar.swift
  CodeEditModules/Modules/Feedback/src/Model/FeedbackModel.swift
  CodeEditModules/Modules/Feedback/src/Model/FeedbackType.swift
  CodeEditModules/Modules/Feedback/src/Model/IssueArea.swift
  CodeEditModules/Package.swift
Labels: enhancement, WIP

#465 Add ability to load Language Servers as extensions (bundles)
  CodeEdit/Info.plist
  CodeEditModules/Modules/ExtensionsStore/src/ExtensionsManager.swift
  CodeEditModules/Modules/ExtensionsStore/src/Models/DownloadedPlugin.swift
  CodeEditModules/Modules/ExtensionsStore/src/Models/Plugin.swift
  CodeEditModules/Modules/LSP/src/LSPClient.swift
  CodeEditModules/Package.swift
Labels: enhancement, extensions, editor

#468 Added `vault` and `vault.fill` custom symbols for `source control` references
  CodeEdit/AppDelegate.swift
  CodeEdit/Assets.xcassets/Custom Colors/Contents.json
  CodeEdit/Assets.xcassets/Custom Colors/SidebarYellow.colorset/Contents.json
  CodeEdit/Assets.xcassets/Custom Symbols/Contents.json
  CodeEdit/Assets.xcassets/Custom Symbols/vault.fill.symbolset/Contents.json
  CodeEdit/Assets.xcassets/Custom Symbols/vault.fill.symbolset/vault.fill.svg
  CodeEdit/Assets.xcassets/Custom Symbols/vault.symbolset/Contents.json
  CodeEdit/Assets.xcassets/Custom Symbols/vault.symbolset/vault.svg
  CodeEdit/NavigatorSidebar/NavigatorSidebarToolbarTop.swift
Labels: UI

#472 Added package `CodeEditSymbols`
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CodeEdit/AppDelegate.swift
  CodeEdit/Assets.xcassets/Custom Symbols/Contents.json
  CodeEdit/Assets.xcassets/Custom Symbols/vault.fill.symbolset/Contents.json
  CodeEdit/Assets.xcassets/Custom Symbols/vault.fill.symbolset/vault.fill.svg
  CodeEdit/Assets.xcassets/Custom Symbols/vault.symbolset/Contents.json
  CodeEdit/Assets.xcassets/Custom Symbols/vault.symbolset/vault.svg
  CodeEdit/Info.plist
  CodeEdit/NavigatorSidebar/NavigatorSidebarToolbarTop.swift
  CodeEditModules/Package.swift
Labels: enhancement

#460 Branch checkout after cloning
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit/Info.plist
  CodeEditModules/Modules/GitClient/src/Interface.swift
  CodeEditModules/Modules/GitClient/src/Live.swift
  CodeEditModules/Modules/GitClone/src/CheckoutBranch.swift
  CodeEditModules/Modules/GitClone/src/CheckoutBranchView.swift
  CodeEditModules/Modules/GitClone/src/GitCloneView.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarItems/StatusBarBranchPicker.swift
  CodeEditModules/Modules/WelcomeModule/src/WelcomeView.swift
Labels: WIP

#461 Fix and Fine-tune Tab Bar Styles and Interaction Effects
  CodeEdit/TabBar/TabBar.swift
  CodeEdit/TabBar/TabBarItem.swift
  CodeEditModules/Modules/AppPreferences/src/Model/General/GeneralPreferences.swift
  CodeEditModules/Modules/AppPreferences/src/Sections/GeneralPreferences/GeneralPreferencesView.swift
Labels: WIP

#481 Added DocC documentation for `CodeEditUI`
  CodeEdit.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CodeEdit/Info.plist
  CodeEdit/TabBar/TabBar.swift
  CodeEdit/TabBar/TabBarItem.swift
  CodeEditModules/Modules/AppPreferences/src/HelperViews/PreferencesToolbar.swift
  CodeEditModules/Modules/AppPreferences/src/Model/AppPreferences.swift
  CodeEditModules/Modules/AppPreferences/src/Sections/AccountsPreferences/PreferenceAccountsView.swift
  CodeEditModules/Modules/AppPreferences/src/Sections/SourceControlPreferences/SourceControlGeneralView.swift
  CodeEditModules/Modules/AppPreferences/src/Sections/SourceControlPreferences/SourceControlGitView.swift
  CodeEditModules/Modules/AppPreferences/src/Sections/ThemePreferences/EditorThemeView.swift
  CodeEditModules/Modules/AppPreferences/src/Sections/ThemePreferences/PreviewThemeView.swift
  CodeEditModules/Modules/AppPreferences/src/Sections/ThemePreferences/TerminalThemeView.swift
  CodeEditModules/Modules/AppPreferences/src/Sections/ThemePreferences/ThemePreferencesView.swift
  CodeEditModules/Modules/CodeEditUI/src/Documentation.docc/Documentation.md
  CodeEditModules/Modules/CodeEditUI/src/EffectView.swift
  CodeEditModules/Modules/CodeEditUI/src/FontPickerView.swift
  CodeEditModules/Modules/CodeEditUI/src/HelpButton.swift
  CodeEditModules/Modules/CodeEditUI/src/SegmentedControl.swift
  CodeEditModules/Modules/QuickOpen/src/QuickOpenView.swift
  CodeEditModules/Modules/WelcomeModule/src/RecentProjectsView.swift
Labels: documentation

#423 [WIP] #350 Bottom Drawer
  CodeEdit/Assets.xcassets/custom.breakpoint.fill.symbolset/Contents.json
  CodeEdit/Assets.xcassets/custom.breakpoint.fill.symbolset/custom.breakpoint.fill.svg
  CodeEdit/Assets.xcassets/custom.breakpoint.symbolset/Contents.json
  CodeEdit/Assets.xcassets/custom.breakpoint.symbolset/custom.breakpoint.svg
  CodeEdit/Documents/WorkspaceDocument.swift
  CodeEdit/WorkspaceView.swift
  CodeEditModules/Modules/StatusBar/src/Model/StatusBarModel.swift
  CodeEditModules/Modules/StatusBar/src/StatusBar.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarItems/FilterTextField.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarItems/StatusBarBreakpointButton.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarItems/StatusBarClearButton.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarItems/StatusBarDrawer.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarItems/StatusBarMaximizeButton.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarItems/StatusBarSplitTerminalButton.swift
  CodeEditModules/Package.swift
Labels: UI, statusbar, WIP

#486 Moved `breakpoint` & `breakpoint.fill` symbols to `CodeEditSymbols`
  CodeEdit.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CodeEdit/Assets.xcassets/custom.breakpoint.fill.symbolset/Contents.json
  CodeEdit/Assets.xcassets/custom.breakpoint.fill.symbolset/custom.breakpoint.fill.svg
  CodeEdit/Assets.xcassets/custom.breakpoint.symbolset/Contents.json
  CodeEdit/Assets.xcassets/custom.breakpoint.symbolset/custom.breakpoint.svg
  CodeEdit/Info.plist
  CodeEditModules/Modules/StatusBar/src/StatusBarItems/StatusBarBreakpointButton.swift
  CodeEditModules/Package.swift
Labels: Other

#488 fix `breakpoint.fill` symbol scaling issue
  CodeEdit.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CodeEdit/Info.plist
Labels: Other

#490 quick fix extensions menu item opening about window
  CodeEdit/MainMenu.xib
Labels: bug

#494 Fix: `History Inspector` selection, UI Enhancements
  CodeEdit/Info.plist
  CodeEdit/InspectorSidebar/Views/HistoryInspector.swift
  CodeEdit/InspectorSidebar/Views/HistoryItem.swift
  CodeEdit/InspectorSidebar/Views/Popover/PopoverView.swift
  CodeEditModules/Modules/CodeEditUtils/src/Extensions/Date+Formatted.swift
  CodeEditModules/Modules/CodeEditUtils/src/Extensions/String+MD5.swift
Labels: bug, UI

#502 Fixes: History Inspector
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit/Assets.xcassets/Custom Colors/HistoryInspectorHash.colorset/Contents.json
  CodeEdit/Assets.xcassets/Custom Colors/HistoryInspectorPopover.colorset/Contents.json
  CodeEdit/Extensions/NSTableView+Background.swift
  CodeEdit/Info.plist
  CodeEdit/InspectorSidebar/InspectorSidebar.swift
  CodeEdit/InspectorSidebar/Views/HistoryItem.swift
  CodeEdit/InspectorSidebar/Views/Popover/PopoverView.swift
  CodeEditModules/Modules/AppPreferences/src/Sections/AccountsPreferences/PreferenceAccountsView.swift
  CodeEditModules/Modules/GitClient/src/Live.swift
Labels: bug, UI

#503 fix history inspector: `not a git repo`
  CodeEdit/Info.plist
  CodeEditModules/Modules/GitClient/src/Live.swift
Labels: bug

#507 History Inspector: Support to `View on BitBucket`
  CodeEdit/Info.plist
  CodeEdit/InspectorSidebar/Views/HistoryItem.swift
  CodeEditModules/Modules/GitClient/src/Models/Commit.swift
Labels: WIP

#482 `CodeEditUI`: Added snapshot tests & Keep CircleCI?
  .circleci/config.yml
  CodeEdit.xcodeproj/xcshareddata/xcschemes/CodeEdit.xcscheme
  CodeEdit/Info.plist
  CodeEditModules/Modules/CodeEditUI/Tests/UnitTests.swift
  CodeEditModules/Modules/CodeEditUI/Tests/__Snapshots__/UnitTests/testEffectViewDark.1.png
  CodeEditModules/Modules/CodeEditUI/Tests/__Snapshots__/UnitTests/testEffectViewLight.1.png
  CodeEditModules/Modules/CodeEditUI/Tests/__Snapshots__/UnitTests/testFontPickerViewDark.1.png
  CodeEditModules/Modules/CodeEditUI/Tests/__Snapshots__/UnitTests/testFontPickerViewLight.1.png
  CodeEditModules/Modules/CodeEditUI/Tests/__Snapshots__/UnitTests/testHelpButtonDark.1.png
  CodeEditModules/Modules/CodeEditUI/Tests/__Snapshots__/UnitTests/testHelpButtonLight.1.png
  CodeEditModules/Modules/CodeEditUI/Tests/__Snapshots__/UnitTests/testSegmentedControlDark.1.png
  CodeEditModules/Modules/CodeEditUI/Tests/__Snapshots__/UnitTests/testSegmentedControlLight.1.png
  CodeEditModules/Package.swift
Labels: Other

#509 Docs: enhanced docs for `CodeEditUI` including component previews.
  CodeEdit/Info.plist
  CodeEditModules/Modules/CodeEditUI/src/Documentation.docc/FontPicker.md
  CodeEditModules/Modules/CodeEditUI/src/Documentation.docc/HelpButton.md
  CodeEditModules/Modules/CodeEditUI/src/Documentation.docc/Resources/FontPicker_View.png
  CodeEditModules/Modules/CodeEditUI/src/Documentation.docc/Resources/HelpButton_View.png
  CodeEditModules/Modules/CodeEditUI/src/Documentation.docc/Resources/SegmentedControl_View.png
  CodeEditModules/Modules/CodeEditUI/src/Documentation.docc/SegmentedControl.md
  CodeEditModules/Modules/CodeEditUI/src/FontPickerView.swift
  CodeEditModules/Modules/CodeEditUI/src/HelpButton.swift
  CodeEditModules/Modules/CodeEditUI/src/SegmentedControl.swift
Labels: documentation

#511 Editor: Respect Font from Preferences
  CodeEdit/Info.plist
  CodeEditModules/Modules/AppPreferences/src/Model/Terminal/TerminalPreferences.swift
  CodeEditModules/Modules/AppPreferences/src/Model/Text Editing/TextEditingPreferences.swift
  CodeEditModules/Modules/CodeFile/src/CodeEditor.swift
Labels: UI, editor

#510 Tests: Re-enabled all Unit/Snapshot Tests
  CodeEdit.xcodeproj/xcshareddata/xcschemes/CodeEdit.xcscheme
  CodeEditModules/Modules/GitClient/Tests/GitClientTests.swift
  CodeEditModules/Modules/WelcomeModule/Tests/UnitTests.swift
  CodeEditModules/Modules/WelcomeModule/Tests/__Snapshots__/UnitTests/testRecentJSFileDarkSnapshot.1.png
  CodeEditModules/Modules/WelcomeModule/Tests/__Snapshots__/UnitTests/testRecentJSFileLightSnapshot.1.png
  CodeEditModules/Modules/WelcomeModule/Tests/__Snapshots__/UnitTests/testRecentProjectItemDarkSnapshot.1.png
  CodeEditModules/Modules/WelcomeModule/Tests/__Snapshots__/UnitTests/testRecentProjectItemLightSnapshot.1.png
  CodeEditModules/Modules/WelcomeModule/Tests/__Snapshots__/UnitTests/testWelcomeActionViewDarkSnapshot.1.png
  CodeEditModules/Modules/WelcomeModule/Tests/__Snapshots__/UnitTests/testWelcomeActionViewLightSnapshot.1.png
  CodeEditModules/Package.swift
Labels: tests

#516 Added support for ssh based origins
  CodeEdit/Info.plist
  CodeEditModules/Modules/GitClient/src/Models/Commit.swift
Labels: enhancement

#514 Fix Tab-switching Keyboard Shortcut Issue
  CodeEdit/TabBar/TabBarItem.swift
Labels: bug

#517 FEAT: Toolbar Branch Picker
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit.xcodeproj/xcshareddata/xcschemes/CodeEdit.xcscheme
  CodeEdit/Documents/CodeEditWindowController.swift
  CodeEdit/Info.plist
  CodeEditModules/Modules/CodeEditUI/src/BranchPickerToolbarItem.swift
  CodeEditModules/Modules/GitClient/Tests/GitClientTests.swift
  CodeEditModules/Modules/GitClient/src/Live.swift
  CodeEditModules/Modules/StatusBar/src/StatusBar.swift
  CodeEditModules/Package.swift
Labels: enhancement, UI

#518 ToolbarBranchPicker: docs, tests and renamed
  CodeEdit/Documents/CodeEditWindowController.swift
  CodeEdit/Info.plist
  CodeEditModules/Modules/CodeEditUI/Tests/UnitTests.swift
  CodeEditModules/Modules/CodeEditUI/Tests/__Snapshots__/UnitTests/testBranchPickerDark.1.png
  CodeEditModules/Modules/CodeEditUI/Tests/__Snapshots__/UnitTests/testBranchPickerLight.1.png
  CodeEditModules/Modules/CodeEditUI/src/Documentation.docc/Documentation.md
  CodeEditModules/Modules/CodeEditUI/src/Documentation.docc/Resources/BranchPicker_View.png
  CodeEditModules/Modules/CodeEditUI/src/Documentation.docc/ToolbarBranchPicker.md
  CodeEditModules/Modules/CodeEditUI/src/ToolbarBranchPicker.swift
Labels: documentation

#525 Match Tab Bar Divider Colors and Width
  CodeEdit/Documents/WorkspaceCodeFileView.swift
  CodeEdit/TabBar/TabBar.swift
  CodeEdit/TabBar/TabBarItem.swift
Labels: UI

#527 Toolbar: Branch Picker fixes
  CodeEdit/Info.plist
  CodeEditModules/Modules/CodeEditUI/Tests/__Snapshots__/UnitTests/testBranchPickerDark.1.png
  CodeEditModules/Modules/CodeEditUI/Tests/__Snapshots__/UnitTests/testBranchPickerLight.1.png
  CodeEditModules/Modules/CodeEditUI/src/ToolbarBranchPicker.swift
Labels: bug, UI

#529 Toolbar: update on branch changes, Icon update for projects w/out git repo
  CodeEdit/Info.plist
  CodeEditModules/Modules/CodeEditUI/Tests/__Snapshots__/UnitTests/testBranchPickerDark.1.png
  CodeEditModules/Modules/CodeEditUI/Tests/__Snapshots__/UnitTests/testBranchPickerLight.1.png
  CodeEditModules/Modules/CodeEditUI/src/ToolbarBranchPicker.swift
Labels: bug, UI

#530 History & Branch Selector Popover: fixed selection background colors
  CodeEdit/Info.plist
  CodeEdit/InspectorSidebar/Views/Popover/PopoverView.swift
  CodeEditModules/Modules/CodeEditUI/src/EffectView.swift
  CodeEditModules/Modules/CodeEditUI/src/ToolbarBranchPicker.swift
Labels: UI

#537 Editor View: Updated Font for Line Numbers
  CodeEdit/Info.plist
  CodeEditModules/Modules/CodeFile/src/CodeEditor.swift
  CodeEditModules/Modules/CodeFile/src/LineGutter/LineGutter.swift
Labels: UI, editor

#539 Editor: Apply Theme Colors
  CodeEdit.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CodeEdit/Info.plist
  CodeEditModules/Modules/AppPreferences/src/Extensions/Color+HEX.swift
  CodeEditModules/Modules/AppPreferences/src/Model/Theme/ThemePreferences.swift
  CodeEditModules/Modules/AppPreferences/src/Sections/ThemePreferences/Model/Theme+Highlightr.swift
  CodeEditModules/Modules/CodeEditUtils/src/Extensions/Color+HEX.swift
  CodeEditModules/Modules/CodeEditUtils/src/Extensions/String+RemoveOccurances.swift
  CodeEditModules/Modules/CodeFile/src/CodeEditor.swift
  CodeEditModules/Modules/CodeFile/src/CodeFileView.swift
  CodeEditModules/Modules/CodeFile/src/Model/Theme.swift
  CodeEditModules/Package.swift
Labels: enhancement, UI, editor

#544 Themes: New bundled default themes
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit/DefaultThemes/codeedit-xcode-dark.json
  CodeEdit/DefaultThemes/codeedit-xcode-light.json
  CodeEdit/DefaultThemes/default-dark.json
  CodeEdit/Info.plist
  CodeEditModules/Modules/AppPreferences/src/Model/AppPreferencesModel.swift
  CodeEditModules/Modules/AppPreferences/src/Model/Theme/ThemePreferences.swift
  CodeEditModules/Modules/AppPreferences/src/Sections/ThemePreferences/Model/Theme+Highlightr.swift
  CodeEditModules/Modules/AppPreferences/src/Sections/ThemePreferences/Model/Theme.swift
  CodeEditModules/Modules/AppPreferences/src/Sections/ThemePreferences/Model/ThemeModel.swift
  CodeEditModules/Modules/AppPreferences/src/Sections/ThemePreferences/ThemePreferencesView.swift
  CodeEditModules/Modules/AppPreferences/src/Sections/ThemePreferences/ThemePreviewIcon.swift
  CodeEditModules/Modules/CodeFile/src/CodeEditor.swift
Labels: UI, editor, preferences

#547 Themes: GitHub Themes
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit/DefaultThemes/codeedit-github-dark.json
  CodeEdit/DefaultThemes/codeedit-github-light.json
  CodeEdit/DefaultThemes/codeedit-xcode-dark.json
  CodeEdit/DefaultThemes/codeedit-xcode-light.json
  CodeEdit/Info.plist
Labels: UI, editor

#553 Status Bar fixes
  CodeEdit/Info.plist
  CodeEditModules/Modules/StatusBar/src/Model/StatusBarModel.swift
  CodeEditModules/Modules/StatusBar/src/StatusBar.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarItems/StatusBarDrawer.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarItems/StatusBarEncodingSelector.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarItems/StatusBarIndentSelector.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarItems/StatusBarLineEndSelector.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarItems/StatusBarMenuLabel.swift
  CodeEditModules/Modules/TerminalEmulator/src/TerminalEmulatorView.swift
Labels: UI, statusbar, drawer

#552 Theme docs & GitHub Theme Terminal Colors
  CodeEdit/DefaultThemes/codeedit-github-dark.json
  CodeEdit/DefaultThemes/codeedit-github-light.json
  CodeEdit/Info.plist
  CodeEditModules/Modules/AppPreferences/src/Documentation.docc/Themes.md
Labels: documentation, UI

#554 Status Bar Enhancements
  CodeEdit/Info.plist
  CodeEditModules/Modules/StatusBar/src/StatusBar.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarItems/StatusBarCursorLocationLabel.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarItems/StatusBarDrawer.swift
Labels: UI, statusbar, drawer

#558 Statusbar Height & Position fixes
  CodeEdit/Documents/WorkspaceCodeFileView.swift
  CodeEdit/Info.plist
  CodeEdit/NavigatorSidebar/NavigatorSidebarToolbarBottom.swift
  CodeEditModules/Modules/CodeFile/src/CodeEditor.swift
  CodeEditModules/Modules/StatusBar/src/StatusBar.swift
  CodeEditModules/Modules/StatusBar/src/StatusBarItems/StatusBarDrawer.swift
Labels: UI, statusbar, drawer

#560 [WIP] Add missing general preferences
  CodeEditModules/Modules/AppPreferences/src/HelperViews/PreferencesSection.swift
  CodeEditModules/Modules/AppPreferences/src/Model/General/GeneralPreferences.swift
  CodeEditModules/Modules/AppPreferences/src/Sections/GeneralPreferences/GeneralPreferencesView.swift
Labels: UI, WIP

#568 [WIP] TextField focus effect in FindNavigatorSearchBar
  CodeEdit/NavigatorSidebar/FindNavigator/FindNavigatorSearchBar.swift
Labels: UI, WIP
