Repository CodeEditApp/CodeEdit, pull requests merged in 2023-03, with the labels that each got.

#1112 Fix for vertical scroller in project navigator
  CodeEdit/Features/NavigatorSidebar/ProjectNavigator/OutlineView/OutlineViewController.swift
Labels: bug

#1114 Fix for excessive files in recents list
  CodeEdit/Features/Documents/Controllers/CodeEditDocumentController.swift
Labels: bug

#1080 Splitview
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CodeEdit/Features/AppPreferences/Model/AppPreferencesModel.swift
  CodeEdit/Features/Breadcrumbs/Views/BreadcrumbsComponent.swift
  CodeEdit/Features/Breadcrumbs/Views/BreadcrumbsView.swift
  CodeEdit/Features/CodeFile/CodeFileView.swift
  CodeEdit/Features/Documents/Controllers/CodeEditWindowController.swift
  CodeEdit/Features/Documents/Views/WorkspaceCodeFileView.swift
  CodeEdit/Features/Documents/WorkspaceDocument+Selection.swift
  CodeEdit/Features/Documents/WorkspaceDocument.swift
  CodeEdit/Features/InspectorSidebar/InspectorSidebarView.swift
  CodeEdit/Features/Keybindings/ModifierKeysObserver.swift
  CodeEdit/Features/NavigatorSidebar/ExtensionNavigator/ExtensionNavigatorItemView.swift
  CodeEdit/Features/NavigatorSidebar/ExtensionNavigator/ExtensionNavigatorView.swift
  CodeEdit/Features/NavigatorSidebar/FindNavigator/FindNavigatorResultList/FindNavigatorListViewController.swift
  CodeEdit/Features/NavigatorSidebar/NavigatorSidebarToolbarBottom.swift
  CodeEdit/Features/NavigatorSidebar/ProjectNavigator/OutlineView/OutlineMenu.swift
  CodeEdit/Features/NavigatorSidebar/ProjectNavigator/OutlineView/OutlineView.swift
  CodeEdit/Features/NavigatorSidebar/ProjectNavigator/OutlineView/OutlineViewController.swift
  CodeEdit/Features/NavigatorSidebar/ProjectNavigator/OutlineView/OutlintViewController+OutlineTableViewCellDelegate.swift
  CodeEdit/Features/NavigatorSidebar/ProjectNavigator/ProjectNavigatorView.swift
  CodeEdit/Features/SplitView/EditorView.swift
  CodeEdit/Features/SplitView/Environment+ContentInsets.swift
  CodeEdit/Features/SplitView/Environment+SplitEditor.swift
  CodeEdit/Features/SplitView/SplitView.swift
  CodeEdit/Features/SplitView/SplitViewControllerView.swift
  CodeEdit/Features/SplitView/SplitViewData.swift
  CodeEdit/Features/SplitView/SplitViewItem.swift
  CodeEdit/Features/SplitView/SplitViewModifiers.swift
  CodeEdit/Features/SplitView/SplitViewReader.swift
  CodeEdit/Features/SplitView/Variadic.swift
  CodeEdit/Features/StatusBar/ViewModels/StatusBarViewModel.swift
  CodeEdit/Features/StatusBar/Views/StatusBarDrawer/StatusBarDrawer.swift
  CodeEdit/Features/StatusBar/Views/StatusBarItems/StatusBarToggleDrawerButton.swift
  CodeEdit/Features/StatusBar/Views/StatusBarView.swift
  CodeEdit/Features/Tabs/Models/TabBarItemID.swift
  CodeEdit/Features/Tabs/Models/TabBarItemRepresentable.swift
  CodeEdit/Features/Tabs/Models/TabManager.swift
  CodeEdit/Features/Tabs/TabGroup/Environment+ActiveTabGroup.swift
  CodeEdit/Features/Tabs/TabGroup/TabGroup.swift
  CodeEdit/Features/Tabs/TabGroup/TabGroupData.swift
  CodeEdit/Features/Tabs/TabGroup/WorkspaceTabGroupView.swift
  CodeEdit/Features/Tabs/Views/TabBarAccessory.swift
  CodeEdit/Features/Tabs/Views/TabBarContextMenu.swift
  CodeEdit/Features/Tabs/Views/TabBarDivider.swift
  CodeEdit/Features/Tabs/Views/TabBarItemBackground.swift
  CodeEdit/Features/Tabs/Views/TabBarItemButtonStyle.swift
  CodeEdit/Features/Tabs/Views/TabBarItemCloseButton.swift
  CodeEdit/Features/Tabs/Views/TabBarItemView.swift
  CodeEdit/Features/Tabs/Views/TabBarNative.swift
  CodeEdit/Features/Tabs/Views/TabBarView.swift
  CodeEdit/Features/Tabs/Views/TabBarXcode.swift
  CodeEdit/Utils/WorkspaceClient/Model/FileItem.swift
  CodeEdit/WindowObserver.swift
  CodeEdit/WorkspaceView.swift
Labels: enhancement

#1123 [chore]: Update Version Number to `0.0.3`
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit/Info.plist
  OpenWithCodeEdit/Info.plist
Labels: chore

#1124 Fix for appcast link
  CodeEdit/Info.plist
Labels: bug

#1113 Rename `Breadcrumbs` to `PathBar` and fix comments
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit/Features/AppPreferences/Model/Terminal/TerminalPreferences.swift
  CodeEdit/Features/AppPreferences/Sections/KeybindingsPreferences/KeybindingsPreferencesView.swift
  CodeEdit/Features/AppPreferences/Sections/ThemePreferences/Model/Theme.swift
  CodeEdit/Features/CodeFile/CodeFile.swift
  CodeEdit/Features/Commands/ViewModels/CommandPaletteViewModel.swift
  CodeEdit/Features/Documents/Views/WorkspaceCodeFileView.swift
  CodeEdit/Features/Git/Client/Models/GitCommit.swift
  CodeEdit/Features/Keybindings/CommandManager.swift
  CodeEdit/Features/Keybindings/KeybindingManager.swift
  CodeEdit/Features/NavigatorSidebar/NavigatorSidebarToolbarTop.swift
  CodeEdit/Features/PathBar/Views/PathBarComponent.swift
  CodeEdit/Features/PathBar/Views/PathBarMenu.swift
  CodeEdit/Features/PathBar/Views/PathBarView.swift
  CodeEdit/Features/QuickOpen/ViewModels/QuickOpenViewModel.swift
  CodeEdit/Features/SplitView/SplitView.swift
  CodeEdit/Features/SplitView/SplitViewControllerView.swift
  CodeEdit/Features/SplitView/SplitViewData.swift
  CodeEdit/Features/StatusBar/ViewModels/StatusBarViewModel.swift
  CodeEdit/Features/Tabs/TabGroup/WorkspaceTabGroupView.swift
  CodeEdit/Features/TerminalEmulator/TerminalEmulatorView.swift
  CodeEdit/Utils/Environment/Env+IsFullscreen.swift
  CodeEdit/Utils/Environment/Env+Window.swift
  Documentation.docc/App Window/App Window.md
  Documentation.docc/AppPreferences/Getting Started.md
Labels: documentation, breadcrumbs

#1132 Fix for retain cycles & splitview recreation issue
  CodeEdit/Features/PathBar/Views/PathBarComponent.swift
  CodeEdit/Features/SplitView/EditorView.swift
  CodeEdit/Features/SplitView/SplitView.swift
  CodeEdit/Features/SplitView/SplitViewControllerView.swift
  CodeEdit/Features/SplitView/SplitViewItem.swift
  CodeEdit/Features/SplitView/SplitViewModifiers.swift
  CodeEdit/Features/SplitView/SplitViewReader.swift
  CodeEdit/Features/Tabs/TabGroup/WorkspaceTabGroupView.swift
  CodeEdit/Features/Tabs/Views/TabBarView.swift
Labels: bug

#1157 🧹 Refactor of the WorkspaceClient
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit/Features/CEWorkspace/Models/CEWorkspaceFile.swift
  CodeEdit/Features/CEWorkspace/Models/CEWorkspaceFileIcon.swift
  CodeEdit/Features/CEWorkspace/Models/CEWorkspaceFileManager.swift
  CodeEdit/Features/CodeEditUI/Views/ToolbarBranchPicker.swift
  CodeEdit/Features/Documents/Controllers/CodeEditWindowController.swift
  CodeEdit/Features/Documents/Views/WorkspaceCodeFileView.swift
  CodeEdit/Features/Documents/WorkspaceDocument+Listeners.swift
  CodeEdit/Features/Documents/WorkspaceDocument+Search.swift
  CodeEdit/Features/Documents/WorkspaceDocument.swift
  CodeEdit/Features/ExtensionsStore/Models/Plugin.swift
  CodeEdit/Features/NavigatorSidebar/FindNavigator/FindNavigatorResultList/FindNavigatorListViewController.swift
  CodeEdit/Features/NavigatorSidebar/NavigatorSidebarToolbarBottom.swift
  CodeEdit/Features/NavigatorSidebar/ProjectNavigator/OutlineView/OutlineMenu.swift
  CodeEdit/Features/NavigatorSidebar/ProjectNavigator/OutlineView/OutlineTableViewCell.swift
  CodeEdit/Features/NavigatorSidebar/ProjectNavigator/OutlineView/OutlineView.swift
  CodeEdit/Features/NavigatorSidebar/ProjectNavigator/OutlineView/OutlineViewController.swift
  CodeEdit/Features/NavigatorSidebar/ProjectNavigator/OutlineView/OutlintViewController+OutlineTableViewCellDelegate.swift
  CodeEdit/Features/NavigatorSidebar/ProjectNavigator/ProjectNavigatorView.swift
  CodeEdit/Features/PathBar/Views/PathBarComponent.swift
  CodeEdit/Features/PathBar/Views/PathBarMenu.swift
  CodeEdit/Features/PathBar/Views/PathBarView.swift
  CodeEdit/Features/QuickOpen/ViewModels/QuickOpenViewModel.swift
  CodeEdit/Features/QuickOpen/Views/QuickOpenItem.swift
  CodeEdit/Features/QuickOpen/Views/QuickOpenPreviewView.swift
  CodeEdit/Features/QuickOpen/Views/QuickOpenView.swift
  CodeEdit/Features/Search/Model/SearchResultMatchModel.swift
  CodeEdit/Features/Search/Model/SearchResultModel.swift
  CodeEdit/Features/StatusBar/Views/StatusBarDrawer/StatusBarDrawer.swift
  CodeEdit/Features/Tabs/Models/TabBarItemRepresentable.swift
  CodeEdit/Features/Tabs/Models/TabManager.swift
  CodeEdit/Features/Tabs/TabGroup/TabGroup.swift
  CodeEdit/Features/Tabs/TabGroup/TabGroupData.swift
  CodeEdit/Features/Tabs/Views/TabBarContextMenu.swift
  CodeEdit/Features/Tabs/Views/TabBarItemView.swift
  CodeEdit/Features/Tabs/Views/TabBarView.swift
  CodeEdit/Utils/Extensions/Array/Array+CEWorkspaceFile.swift
  CodeEdit/Utils/WorkspaceClient/Interface.swift
  CodeEdit/Utils/WorkspaceClient/Live.swift
  CodeEdit/Utils/WorkspaceClient/Mocks.swift
  CodeEdit/Utils/WorkspaceClient/Model/FileItem+Array.swift
  CodeEdit/Utils/WorkspaceClient/Model/FileItem.swift
  CodeEdit/WorkspaceView.swift
Labels: chore

#1168 Remove Welcome Window reopening after last document is closed
  CodeEdit/Features/Documents/Controllers/CodeEditDocumentController.swift
Labels: enhancement

#1169 Files & folders dropped on Welcome Window are opened
  CodeEdit/Features/Documents/WorkspaceDocument.swift
  CodeEdit/Features/Welcome/Views/WelcomeWindowView.swift
Labels: enhancement

#1177 Fixed bug where about window wouldn’t open
  CodeEdit/Features/WindowCommands/MainCommands.swift
Labels: bug

#1192 Fix Inspector toggling
  CodeEdit/Features/Documents/Controllers/CodeEditWindowController.swift
  CodeEdit/Features/WindowCommands/CodeEditCommands.swift
  CodeEdit/Features/WindowCommands/ViewCommands.swift
Labels: bug

#1196 [chore]: Update `CodeEditTextView`, Remove unused `GRDB`
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CodeEdit.xcodeproj/xcshareddata/xcschemes/CodeEdit.xcscheme
Labels: chore
