Repository CodeEditApp/CodeEdit, pull requests merged in 2023-02, with the labels that each got.

#1063 [chore]: Update dependencies, Bump min deployment target to 13.0
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CodeEdit/Info.plist
  OpenWithCodeEdit/Info.plist
Labels: chore

#1067 Improvements to breadcrumbs
  CodeEdit/Features/Breadcrumbs/Views/BreadcrumbsComponent.swift
  CodeEdit/Features/Breadcrumbs/Views/BreadcrumbsMenu.swift
  CodeEdit/Features/Breadcrumbs/Views/BreadcrumbsView.swift
  CodeEdit/Utils/WorkspaceClient/Model/FileItem.swift
Labels: enhancement

#1039 Improved welcomewindow
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit/AppDelegate.swift
  CodeEdit/Features/Welcome/Views/RecentProjectItem.swift
  CodeEdit/Features/Welcome/Views/RecentProjectsListView.swift
  CodeEdit/Features/Welcome/Views/RecentProjectsView.swift
  CodeEdit/Features/Welcome/Views/WelcomeWindowView.swift
  CodeEditTests/Features/Welcome/WelcomeTests-Bridging-Header.h
  CodeEditTests/Features/Welcome/WelcomeTests.swift
  CodeEditTests/Features/Welcome/__Snapshots__/UnitTests/testRecentJSFileDarkSnapshot.1.png
  CodeEditTests/Features/Welcome/__Snapshots__/UnitTests/testRecentJSFileLightSnapshot.1.png
  CodeEditTests/Features/Welcome/__Snapshots__/UnitTests/testRecentProjectItemDarkSnapshot.1.png
  CodeEditTests/Features/Welcome/__Snapshots__/UnitTests/testRecentProjectItemLightSnapshot.1.png
  CodeEditTests/Features/Welcome/__Snapshots__/UnitTests/testWelcomeActionViewDarkSnapshot.1.png
  CodeEditTests/Features/Welcome/__Snapshots__/UnitTests/testWelcomeActionViewLightSnapshot.1.png
Labels: enhancement

#1068 improvement to window state
  CodeEdit/AppDelegate.swift
Labels: bug
