Repository CodeEditApp/CodeEdit, pull requests merged in 2023-01, with the labels that each got.

#889 [chore]: Pipelines for CI/CD
  .github/workflows/CI-pull-request.yml
  .github/workflows/CI-push-main.yml
  .github/workflows/lint.yml
  .github/workflows/pre-release.yml
  .github/workflows/release-drafter.yml
  .github/workflows/tests.yml
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: tests, chore

#895 [chore]: add bump build number action
  .github/workflows/CI-bump-build-number.yml
  .github/workflows/CI-pre-release.yml
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit/Info.plist
  OpenWithCodeEdit/Info.plist
Labels: chore

#909 [fix]: Sparkle Software Updater
  .github/workflows/pre-release.yml
  CodeEdit/Features/AppPreferences/SoftwareUpdater.swift
  CodeEdit/Info.plist
Labels: bug

#920 fix for icon size
  CodeEdit/Features/Documents/Controllers/CodeEditSplitViewController.swift
  CodeEdit/Features/NavigatorSidebar/NavigatorSidebarToolbarTop.swift
Labels: bug

#922 [fix]: update from menu bar
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit/AppDelegate.swift
  CodeEdit/MainMenu.xib
Labels: bug

#929 [chore]: CI - self hosted runner
  .circleci/config.yml
  .github/workflows/CI-bump-build-number.yml
  .github/workflows/CI-pre-release.yml
  .github/workflows/lint.yml
  .github/workflows/pre-release.yml
  .github/workflows/tests.yml
Labels: chore

#936 Fixed incorrect background colors to be more consistent
  CodeEdit/Features/TabBar/Views/TabBarDivider.swift
  CodeEdit/Features/TabBar/Views/TabBarView.swift
  CodeEdit/WorkspaceView.swift
Labels: UI

#935 [chore]: CI - use semantic versioning for pre-releases
  .github/workflows/pre-release.yml
Labels: chore

#939 [fix]: Update Mechanism
  CodeEdit/Features/AppPreferences/SoftwareUpdater.swift
Labels: bug

#962 Added NSWindow environment key
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit/Features/Documents/Controllers/CodeEditWindowController.swift
  CodeEdit/Features/Documents/Views/WorkspaceCodeFileView.swift
  CodeEdit/Features/InspectorSidebar/InspectorSidebarView.swift
  CodeEdit/Features/NavigatorSidebar/NavigatorSidebarView.swift
  CodeEdit/Features/NavigatorSidebar/ProjectNavigator/ProjectNavigatorView.swift
  CodeEdit/Features/TabBar/Views/TabBarItemView.swift
  CodeEdit/Features/TabBar/Views/TabBarView.swift
  CodeEdit/Utils/Environment/IsFullscreen.swift
  CodeEdit/Utils/Environment/Window.swift
  CodeEdit/WindowObserver.swift
  CodeEdit/WorkspaceView.swift
Labels: enhancement

#963 [fix]: Acknowledgements Window
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CodeEdit/Features/Acknowledgements/ViewModels/AcknowledgementsViewModel.swift
  CodeEdit/Features/Acknowledgements/Views/AcknowledgementsView.swift
  CodeEdit/Features/Acknowledgements/Views/ParsePackagesResolved.swift
  CodeEditTests/Features/Acknowledgements/AcknowledgementsTests.swift
  Package.resolved
Labels: bug

#967 [chore]: Xcode Configurations
  .github/workflows/pre-release.yml
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit/Features/About/Views/AboutView.swift
  CodeEdit/Features/Welcome/Views/WelcomeView.swift
  CodeEdit/Info.plist
  CodeEdit/Utils/Extensions/Bundle/Bundle+Info.swift
  Configs/Alpha.xcconfig
  Configs/Beta.xcconfig
  Configs/Debug.xcconfig
  Configs/Release.xcconfig
Labels: chore

#966 Moved to EnvironmentObject for WorkspaceDocument and StatusBarViewModel
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit/Features/Documents/Views/WorkspaceCodeFileView.swift
  CodeEdit/Features/NavigatorSidebar/ExtensionNavigator/ExtensionNavigatorView.swift
  CodeEdit/Features/NavigatorSidebar/FindNavigator/FindNavigatorResultList/FindNavigatorResultList.swift
  CodeEdit/Features/NavigatorSidebar/FindNavigator/FindNavigatorView.swift
  CodeEdit/Features/NavigatorSidebar/NavigatorSidebarToolbarBottom.swift
  CodeEdit/Features/NavigatorSidebar/NavigatorSidebarView.swift
  CodeEdit/Features/NavigatorSidebar/ProjectNavigator/OutlineView/OutlineView.swift
  CodeEdit/Features/NavigatorSidebar/ProjectNavigator/ProjectNavigatorView.swift
  CodeEdit/Features/NavigatorSidebar/SourceControlNavigator/SourceControlNavigatorView.swift
  CodeEdit/Features/StatusBar/Views/StatusBarDrawer/BottomBar/StatusBarClearButton.swift
  CodeEdit/Features/StatusBar/Views/StatusBarDrawer/BottomBar/StatusBarMaximizeButton.swift
  CodeEdit/Features/StatusBar/Views/StatusBarDrawer/BottomBar/StatusBarSplitTerminalButton.swift
  CodeEdit/Features/StatusBar/Views/StatusBarDrawer/StatusBarDrawer.swift
  CodeEdit/Features/StatusBar/Views/StatusBarItems/StatusBarBreakpointButton.swift
  CodeEdit/Features/StatusBar/Views/StatusBarItems/StatusBarCursorLocationLabel.swift
  CodeEdit/Features/StatusBar/Views/StatusBarItems/StatusBarEncodingSelector.swift
  CodeEdit/Features/StatusBar/Views/StatusBarItems/StatusBarIndentSelector.swift
  CodeEdit/Features/StatusBar/Views/StatusBarItems/StatusBarLineEndSelector.swift
  CodeEdit/Features/StatusBar/Views/StatusBarItems/StatusBarMenuLabel.swift
  CodeEdit/Features/StatusBar/Views/StatusBarItems/StatusBarToggleDrawerButton.swift
  CodeEdit/Features/StatusBar/Views/StatusBarView.swift
  CodeEdit/Features/TabBar/Views/TabBarContextMenu.swift
  CodeEdit/Features/TabBar/Views/TabBarItemView.swift
  CodeEdit/Features/TabBar/Views/TabBarView.swift
  CodeEdit/Utils/Environment/Env+IsFullscreen.swift
  CodeEdit/Utils/Environment/Env+Window.swift
  CodeEdit/WorkspaceView.swift
Labels: enhancement

#974 [feat] Default Themes: Solarized (dark/light)
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit/DefaultThemes/codeedit-solarized-dark.json
  CodeEdit/DefaultThemes/codeedit-solarized-light.json
  CodeEdit/Features/AppPreferences/Sections/ThemePreferences/Model/ThemeModel.swift
Labels: enhancement, editor, terminal

#980 fix: Select account provider dialog not closing
  CodeEdit/Features/AppPreferences/Sections/AccountsPreferences/Accounts/AccountSelectionDialog.swift
  CodeEdit/Features/AppPreferences/Sections/AccountsPreferences/Accounts/Login/Github/GitHubEnterpriseLoginView.swift
  CodeEdit/Features/AppPreferences/Sections/AccountsPreferences/Accounts/Login/Github/GitHubLoginView.swift
  CodeEdit/Features/AppPreferences/Sections/AccountsPreferences/Accounts/Login/Gitlab/GitLabHostedLoginView.swift
  CodeEdit/Features/AppPreferences/Sections/AccountsPreferences/Accounts/Login/Gitlab/GitLabLoginView.swift
Labels: bug

#989 Improved overall tab UI design
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit/Features/Breadcrumbs/Views/BreadcrumbsView.swift
  CodeEdit/Features/TabBar/Views/TabBarItemBackground.swift
  CodeEdit/Features/TabBar/Views/TabBarItemCloseButton.swift
  CodeEdit/Features/TabBar/Views/TabBarItemView.swift
  CodeEdit/Features/TabBar/Views/TabBarView.swift
  CodeEdit/Features/TabBar/Views/TabBarXcode.swift
  CodeEdit/WorkspaceView.swift
Labels: enhancement

#993 [chore]: welcome window refactoring
  CodeEdit/Features/Welcome/Views/RecentProjectItem.swift
  CodeEdit/Features/Welcome/Views/RecentProjectsView.swift
  CodeEdit/Features/Welcome/Views/WelcomeView.swift
  CodeEdit/Features/Welcome/Views/WelcomeWindowView.swift
Labels: chore

#994 [chore]: Update CodeEditTextView to 0.3.3
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: chore

#996 Redesigned Acknowledgements Window, small modifications to About Window
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit/Features/About/Views/AboutView.swift
  CodeEdit/Features/About/Views/AboutWindowController.swift
  CodeEdit/Features/Acknowledgements/Views/AcknowledgementsView.swift
  CodeEdit/Features/Acknowledgements/Views/AcknowledgementsWindowController.swift
Labels: enhancement

#1000 Redesigned About Window
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit/Features/About/Views/AboutView.swift
  CodeEdit/Features/About/Views/AboutWindowController.swift
  CodeEdit/Info.plist
  CodeEdit/Utils/Extensions/Text/Font+Caption3.swift
Labels: enhancement, UI

#1006 [chore]: CI - Check CFBundleShortVersionString in Info.plist
  .github/scripts/test_version_number.sh
  .github/workflows/tests.yml
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit/Info.plist
  Configs/Alpha.xcconfig
  Configs/Beta.xcconfig
  Configs/Debug.xcconfig
  Configs/Release.xcconfig
  OpenWithCodeEdit/Info.plist
Labels: chore

#1019 [chore]: Adopt code edit symbols 0.1.2
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: chore

#1022 [feat]: Update CodeEditTextView to 0.3.5 / YAML Support
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: enhancement
