Repository CodeEditApp/CodeEdit, pull requests merged in 2024-03, with the labels that each got.

#1604 Handle Missing Remotes (Git)
  CodeEdit/Features/Git/Client/GitClient+CommitHistory.swift
Labels: bug

#1601 Refactored how themes are stored and loaded
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit/Features/Settings/Pages/ThemeSettings/Models/ThemeModel.swift
  CodeEdit/Features/Settings/Pages/ThemeSettings/ThemeSettingThemeRow.swift
  DefaultThemes/Basic.cetheme
  DefaultThemes/Civic.cetheme
  DefaultThemes/Classic (Dark).cetheme
  DefaultThemes/Classic (Light).cetheme
  DefaultThemes/Default (Dark).cetheme
  DefaultThemes/Default (Light).cetheme
  DefaultThemes/Dusk.cetheme
  DefaultThemes/GitHub (Dark).cetheme
  DefaultThemes/GitHub (Light).cetheme
  DefaultThemes/High Contrast (Dark).cetheme
  DefaultThemes/High Contrast (Light).cetheme
  DefaultThemes/Low Key.cetheme
  DefaultThemes/Midnight.cetheme
  DefaultThemes/Presentation (Dark).cetheme
  DefaultThemes/Presentation (Light).cetheme
  DefaultThemes/Solarized (Dark).cetheme
  DefaultThemes/Solarized (Light).cetheme
  DefaultThemes/Sunset.cetheme
Labels: enhancement

#1611 Git history view now refreshes when opening files from project navigator
  CodeEdit/Features/InspectorArea/HistoryInspector/HistoryInspectorView.swift
Labels: bug

#1609 Fixed delay in synchronization of font size increment and decrement
  CodeEdit/Features/Settings/Models/AppSettings.swift
  CodeEdit/Features/WindowCommands/ViewCommands.swift
Labels: bug

#1603 Navigation style setting and file history navigation improvements
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CodeEdit/Features/CodeEditUI/Views/SegmentedControl.swift
  CodeEdit/Features/Editor/Models/Editor.swift
  CodeEdit/Features/Editor/Models/EditorLayout.swift
  CodeEdit/Features/Editor/Models/EditorManager.swift
  CodeEdit/Features/Editor/PathBar/Views/EditorPathBarView.swift
  CodeEdit/Features/Editor/TabBar/Views/EditorTabBarLeadingAccessories.swift
  CodeEdit/Features/Editor/TabBar/Views/EditorTabBarTrailingAccessories.swift
  CodeEdit/Features/Editor/Views/EditorView.swift
  CodeEdit/Features/NavigatorArea/ProjectNavigator/OutlineView/ProjectNavigatorViewController.swift
  CodeEdit/Features/NavigatorArea/SourceControlNavigator/Views/SourceControlNavigatorView.swift
  CodeEdit/Features/Settings/Models/SettingsData.swift
  CodeEdit/Features/Settings/Pages/NavigationSettings/Models/NavigationSettings.swift
  CodeEdit/Features/Settings/Pages/NavigationSettings/NavigationSettingsView.swift
  CodeEdit/Features/Settings/SettingsView.swift
  CodeEdit/Features/SplitView/Model/SplitViewData.swift
Labels: enhancement, settings

#1614 Recents list in Welcome window now refreshes after opening folders
  CodeEdit/Features/Welcome/Views/RecentProjectsListView.swift
  CodeEdit/Features/Welcome/Views/WelcomeWindow.swift
Labels: bug

#1608 Font Improvement
  CodeEdit/Features/CodeFile/CodeFileView.swift
  CodeEdit/Features/Settings/Pages/TerminalSettings/Models/TerminalSettings.swift
  CodeEdit/Features/Settings/Pages/TerminalSettings/TerminalSettingsView.swift
  CodeEdit/Features/Settings/Pages/TextEditingSettings/Models/TextEditingSettings.swift
  CodeEdit/Features/Settings/Pages/TextEditingSettings/TextEditingSettingsView.swift
  CodeEdit/Features/Settings/Views/MonospacedFontPicker.swift
  CodeEdit/Features/TerminalEmulator/TerminalEmulatorView.swift
Labels: bug

#1627 Fix: Window Actions
  CodeEdit/AppDelegate.swift
  CodeEdit/CodeEditApp.swift
  CodeEdit/Features/Documents/Controllers/CodeEditDocumentController.swift
  CodeEdit/Features/Settings/SettingsWindow.swift
  CodeEdit/Features/Settings/Views/View+ConstrainHeightToWindow.swift
  CodeEdit/Features/Settings/Views/View+HideSidebarToggle.swift
  CodeEdit/Features/Welcome/Views/WelcomeWindow.swift
  CodeEdit/Features/WindowCommands/ExtensionCommands.swift
  CodeEdit/Features/WindowCommands/MainCommands.swift
  CodeEdit/Features/WindowCommands/Utils/CommandsFixes.swift
  CodeEdit/Features/WindowCommands/WindowCommands.swift
  CodeEdit/SceneID.swift
  CodeEdit/Utils/Extensions/NSApplication/NSApp+openWindow.swift
Labels: bug

#1636 Fix toolbar tracking separator
  CodeEdit/Features/Documents/Controllers/CodeEditWindowController.swift
Labels: bug

#1629 Fix: Filename with whitespaces and new lines
  CodeEdit/Features/CEWorkspace/Models/CEWorkspaceFile.swift
Labels: bug

#1631 Remove new window system
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CodeEdit/CodeEditApp.swift
  CodeEdit/Features/Documents/WorkspaceDocument.swift
  CodeEdit/Features/Settings/Models/SettingsData.swift
  CodeEdit/Features/Settings/Models/SettingsPage.swift
  CodeEdit/Features/Settings/Pages/FeatureFlags/FeatureFlagsSettingsView.swift
  CodeEdit/Features/Settings/Pages/FeatureFlags/Models/FeatureFlagsSettings.swift
  CodeEdit/Features/Settings/SettingsView.swift
  CodeEdit/Features/WindowCommands/ViewCommands.swift
  CodeEdit/WindowSplitView.swift
Labels: chore

#1645 File icon improvements
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CodeEdit/Assets.xcassets/Custom Colors/Amber.colorset/Contents.json
  CodeEdit/Assets.xcassets/Custom Colors/Scarlet.colorset/Contents.json
  CodeEdit/Assets.xcassets/Custom Colors/Steel.colorset/Contents.json
  CodeEdit/Features/CEWorkspace/Models/CEWorkspaceFile.swift
  CodeEdit/Features/CEWorkspace/Models/CEWorkspaceFileIcon.swift
  CodeEdit/Features/Editor/PathBar/Views/EditorPathBarMenu.swift
  CodeEdit/Features/Editor/TabBar/Tabs/Tab/EditorTabView.swift
  CodeEdit/Features/NavigatorArea/OutlineView/FileSystemTableViewCell.swift
  CodeEdit/Features/NavigatorArea/SourceControlNavigator/Changes/Views/SourceControlNavigatorChangedFileView.swift
Labels: enhancement
