Repository CodeEditApp/CodeEdit, pull requests merged in 2024-08, with the labels that each got.

#1845 Fixed terminal resize and scroll layout issues, improved utility area toggle animation
  CodeEdit.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CodeEdit/Features/UtilityArea/TerminalUtility/UtilityAreaTerminalView.swift
  CodeEdit/Features/UtilityArea/ViewModels/UtilityAreaViewModel.swift
  CodeEdit/Features/UtilityArea/Views/PaneToolbar.swift
  CodeEdit/Features/UtilityArea/Views/UtilityAreaView.swift
  CodeEdit/WorkspaceView.swift
Labels: enhancement

#1855 Search bar scrolls with the list closes #1818
  CodeEdit/Features/Settings/SettingsView.swift
Labels: enhancement

#1857 fix: Source Control Menu Commit Name
  CodeEdit/Features/NavigatorArea/ProjectNavigator/OutlineView/ProjectNavigatorMenu.swift
Labels: bug

#1843 Fix Terminal State Loss
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CodeEdit/Features/TerminalEmulator/Model/Shell.swift
  CodeEdit/Features/TerminalEmulator/Model/TerminalCache.swift
  CodeEdit/Features/TerminalEmulator/Views/CETerminalView.swift
  CodeEdit/Features/TerminalEmulator/Views/TerminalEmulatorView+Coordinator.swift
  CodeEdit/Features/TerminalEmulator/Views/TerminalEmulatorView.swift
  CodeEdit/Features/UtilityArea/Models/UtilityAreaTerminal.swift
  CodeEdit/Features/UtilityArea/TerminalUtility/UtilityAreaTerminalSidebar.swift
  CodeEdit/Features/UtilityArea/TerminalUtility/UtilityAreaTerminalView.swift
  CodeEdit/Features/UtilityArea/ViewModels/UtilityAreaViewModel.swift
  CodeEdit/Features/UtilityArea/Views/View+paneToolbar.swift
Labels: enhancement, terminal

#1866 Rebuild Cached Files After Rename, Git Status Label
  CodeEdit/Features/CEWorkspace/Models/CEWorkspaceFileManager.swift
  CodeEdit/Features/CEWorkspace/Models/DirectoryEventStream.swift
  CodeEdit/Features/Editor/Models/Editor.swift
  CodeEdit/Features/NavigatorArea/OutlineView/StandardTableViewCell.swift
  CodeEdit/Features/NavigatorArea/ProjectNavigator/OutlineView/ProjectNavigatorViewController+OutlineTableViewCellDelegate.swift
  CodeEdit/Features/NavigatorArea/ProjectNavigator/OutlineView/ProjectNavigatorViewController.swift
Labels: bug

#1865 Mark Autosave Changes Immediately
  CodeEdit/Features/Documents/CodeFileDocument/CodeFileDocument.swift
  CodeEdit/Features/Editor/Views/CodeFileView.swift
Labels: bug

#1858 Fix Source Control File Names With Spaces
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit/Features/CEWorkspace/Models/CEWorkspaceFile.swift
  CodeEdit/Features/CEWorkspace/Models/CEWorkspaceFileIcon.swift
  CodeEdit/Features/Documents/WorkspaceDocument/WorkspaceDocument.swift
  CodeEdit/Features/Editor/Models/EditorManager.swift
  CodeEdit/Features/NavigatorArea/SourceControlNavigator/Changes/Views/SourceControlNavigatorChangedFileView.swift
  CodeEdit/Features/NavigatorArea/SourceControlNavigator/Changes/Views/SourceControlNavigatorChangesCommitView.swift
  CodeEdit/Features/NavigatorArea/SourceControlNavigator/Changes/Views/SourceControlNavigatorChangesList.swift
  CodeEdit/Features/NavigatorArea/SourceControlNavigator/History/Views/CommitChangedFileListItemView.swift
  CodeEdit/Features/NavigatorArea/SourceControlNavigator/History/Views/CommitDetailsView.swift
  CodeEdit/Features/NavigatorArea/SourceControlNavigator/History/Views/SourceControlNavigatorHistoryView.swift
  CodeEdit/Features/NavigatorArea/SourceControlNavigator/Views/ChangedFile/GitChangedFileLabel.swift
  CodeEdit/Features/NavigatorArea/SourceControlNavigator/Views/ChangedFile/GitChangedFileListView.swift
  CodeEdit/Features/Search/Extensions/String+SafeOffset.swift
  CodeEdit/Features/SourceControl/Client/GitClient+Branches.swift
  CodeEdit/Features/SourceControl/Client/GitClient+Commit.swift
  CodeEdit/Features/SourceControl/Client/GitClient+CommitHistory.swift
  CodeEdit/Features/SourceControl/Client/GitClient+Status.swift
  CodeEdit/Features/SourceControl/Client/GitClient.swift
  CodeEdit/Features/SourceControl/Models/GitChangedFile.swift
  CodeEdit/Features/SourceControl/Models/GitStatus.swift
  CodeEdit/Features/SourceControl/SourceControlManager+GitClient.swift
  CodeEdit/Features/SourceControl/SourceControlManager.swift
  CodeEdit/Features/WindowCommands/SourceControlCommands.swift
Labels: bug
