Repository CodeEditApp/CodeEdit, pull requests merged in 2025-04, with the labels that each got.

#2013 Added copy path and copy relative path options in project navigator menu
  CodeEdit/Features/Editor/TabBar/Views/EditorTabBarContextMenu.swift
  CodeEdit/Features/NavigatorArea/ProjectNavigator/OutlineView/ProjectNavigatorMenu.swift
  CodeEdit/Features/NavigatorArea/ProjectNavigator/OutlineView/ProjectNavigatorMenuActions.swift
Labels: enhancement, navigator

#2010 Added editor overscroll setting
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CodeEdit/Features/Editor/Views/CodeFileView.swift
  CodeEdit/Features/Settings/Pages/TextEditingSettings/Models/TextEditingSettings.swift
  CodeEdit/Features/Settings/Pages/TextEditingSettings/TextEditingSettingsView.swift
Labels: enhancement

#2020 [chore:] Update CodeEditSourceEditor, add Find In Editor, Misc Bug Fixes
  CodeEdit.xcodeproj/project.pbxproj
  CodeEdit.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CodeEdit/Features/Editor/Views/CodeFileView.swift
  CodeEdit/Features/Editor/Views/EditorAreaView.swift
  CodeEdit/Features/Settings/Pages/TextEditingSettings/Models/TextEditingSettings.swift
  CodeEdit/Features/Settings/Pages/TextEditingSettings/TextEditingSettingsView.swift
Labels: chore

#2021 [chore:] Bump Version Number
  CodeEdit/Info.plist
  OpenWithCodeEdit/Info.plist
Labels: chore

#2024 Source Control Filter
  CodeEdit/Features/Documents/WorkspaceDocument/WorkspaceDocument.swift
  CodeEdit/Features/NavigatorArea/ProjectNavigator/OutlineView/ProjectNavigatorOutlineView.swift
  CodeEdit/Features/NavigatorArea/ProjectNavigator/OutlineView/ProjectNavigatorViewController+NSOutlineViewDataSource.swift
  CodeEdit/Features/NavigatorArea/ProjectNavigator/OutlineView/ProjectNavigatorViewController.swift
  CodeEdit/Features/NavigatorArea/ProjectNavigator/ProjectNavigatorToolbarBottom.swift
Labels: enhancement
